version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn revolt_annex.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: neondb
      POSTGRES_USER: jperrycode
      POSTGRES_PASSWORD: OYSUEyolux64

volumes:
  postgres_data:
