# Generated by Django 4.2.6 on 2024-01-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
    ]
