# Generated by Django 4.2.6 on 2023-11-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nearby_accomodations',
        ),
    ]
