# Generated by Django 4.2.6 on 2024-01-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VimeoVideo',
        ),
    ]
