# Generated by Django 4.2.6 on 2024-01-03 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveimagefiles',
            name='archive_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_files', to='schedule.archivedshowimagedata'),
        ),
    ]
