# Generated by Django 4.2.6 on 2023-12-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedshowimagedata',
            name='archive_show_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='archiveimagefiles',
            name='archive_image_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='archiveimagefiles',
            name='archive_image_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
