# Generated by Django 4.2.6 on 2024-01-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_archiveimagefiles_archive_img_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visual_artist_listing',
            name='flyer_img_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visual_artist_listing',
            name='flyer_img_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visual_artist_listing',
            name='flyer_server_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
