# Generated by Django 4.2.6 on 2023-12-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_archivedshowimagedata_archive_show_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedshowimagedata',
            name='archive_show_name',
            field=models.CharField(max_length=50),
        ),
    ]
