# Generated by Django 4.2.6 on 2023-11-30 17:00

from django.db import migrations, models
import schedule.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_delete_nearby_accomodations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveimagefiles',
            name='archive_image',
            field=models.ImageField(upload_to=schedule.models.user_directory_path),
        ),
    ]
