# Generated by Django 4.2.1 on 2023-05-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_member_delete_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Artist',
        ),
    ]
