# Generated by Django 4.2.6 on 2023-11-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_delete_nearby_accomodations'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedshowimagedata',
            name='archive_file_upload',
            field=models.FileField(blank=True, upload_to='media/gallery/'),
        ),
    ]
