# Generated by Django 4.2.6 on 2024-01-31 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_visual_artist_listing_flyer_img_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visual_artist_listing',
            options={'ordering': ['-vis_show_date_start'], 'verbose_name': 'Visual Artist', 'verbose_name_plural': 'Visual Artists'},
        ),
    ]
