# Generated by Django 4.2.6 on 2024-01-31 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_visual_artist_listing_flyer_img_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedshowimagedata',
            options={'ordering': ['-archive_end_date'], 'verbose_name': 'Archive', 'verbose_name_plural': 'Archive'},
        ),
    ]
