# Generated by Django 4.2.1 on 2023-05-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_rename_member_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist_listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(blank=True, default='', max_length=50)),
                ('artist_genre', models.CharField(choices=[('rap', 'Rap'), ('Drum and Bass', 'Drum and Bass'), ('House', 'House'), ('Techno', 'Techno'), ('Rock and Roll', 'Rock and Roll'), ('Folk', 'Folk'), ('Scheduled Class', 'Scheduled Class'), ('Bass Music', 'Bass Music'), ('Other', 'Other'), ('UK Grime', 'UK Grime'), ('Hip Hop', 'Hip Hop')], default='', max_length=255)),
                ('show_date', models.DateField()),
                ('artist_bio', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
