# Generated by Django 4.2.6 on 2024-02-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_archivedshowimagedata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedResetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_reset_artist_name', models.CharField(blank=True, max_length=75, null=True)),
                ('archive_reset_support_names', models.CharField(blank=True, max_length=75, null=True)),
                ('archive_reset_show_date', models.DateField(blank=True, null=True)),
                ('archive_reset_artist_web', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Music Archive',
                'verbose_name_plural': 'Music Archive',
                'ordering': ['-archive_reset_show_date'],
            },
        ),
    ]
