# Generated by Django 4.2.6 on 2024-01-31 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_visual_artist_listing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedshowimagedata',
            options={'ordering': ['-archive_end_date'], 'verbose_name': 'Archive', 'verbose_name_plural': 'Archive'},
        ),
        migrations.AlterModelOptions(
            name='visual_artist_listing',
            options={'ordering': ['vis_show_date_start'], 'verbose_name': 'Visual Artist', 'verbose_name_plural': 'Visual Artists'},
        ),
    ]
