# Generated by Django 4.2.6 on 2023-12-24 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_archivedshowimagedata_archive_show_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedshowimagedata',
            name='archive_folder_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='archivedshowimagedata',
            name='archive_show_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='archiveimagefiles',
            name='archive_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.archivedshowimagedata'),
        ),
        migrations.AlterField(
            model_name='archiveimagefiles',
            name='archive_image_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='archiveimagefiles',
            name='archive_image_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
