# Generated by Django 4.2.1 on 2023-05-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_artist_listing_delete_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist_listing',
            name='artist_music',
            field=models.CharField(default='search your self', max_length=200),
        ),
    ]
