# Generated by Django 4.2.1 on 2023-05-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_artist_listing_artist_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist_listing',
            name='entry_price',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
