# Generated by Django 4.2.6 on 2024-02-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_archivedresetdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedresetdata',
            name='archive_reset_artist_web',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
