# Generated by Django 4.2.1 on 2023-05-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_artist_listing_entry_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist_listing',
            name='artist_insta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist_listing',
            name='artist_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist_listing',
            name='entry_price',
            field=models.IntegerField(null=True),
        ),
    ]
