# Generated by Django 4.2.6 on 2024-02-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_remove_music_artist_listing_music_artist_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedresetdata',
            name='archive_reset_bio',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AddField(
            model_name='archivedresetdata',
            name='music_archive_social_url',
            field=models.URLField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='archivedresetdata',
            name='music_archive_soundcloud',
            field=models.URLField(blank=True, max_length=75, null=True),
        ),
    ]
