# Generated by Django 4.2.1 on 2023-05-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_artist_listing_artist_insta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist_listing',
            name='entry_price',
            field=models.FloatField(null=True),
        ),
    ]
