# Generated by Django 4.2.1 on 2023-05-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_artist_listing_entry_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist_listing',
            new_name='Music_artist_listing',
        ),
    ]
