# Generated by Django 4.2.6 on 2024-02-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_archivedresetdata_archive_reset_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music_artist_listing',
            name='artist_music_page',
        ),
    ]
