# Generated by Django 4.2.1 on 2023-05-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_rename_artist_listing_music_artist_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visual_artist_listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(blank=True, default='', max_length=50)),
                ('artist_medium', models.CharField(default='', max_length=255)),
                ('show_date_start', models.DateField()),
                ('show_date_end', models.DateField()),
                ('artist_bio', models.CharField(blank=True, default='', max_length=255)),
                ('artist_website', models.CharField(blank=True, max_length=255, null=True)),
                ('entry_price', models.FloatField(blank=True, null=True)),
                ('age_restricion', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='music_artist_listing',
            old_name='artist_music',
            new_name='artist_music_page',
        ),
    ]
