# Generated by Django 4.2.6 on 2024-02-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_music_artist_listing_reset_flyer_img_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedshowimagedata',
            name='archive_folder_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
