# Generated by Django 4.2.1 on 2023-06-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_alter_music_artist_listing_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_curriucular_listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, default='', max_length=50)),
                ('class_teacher', models.CharField(default='', max_length=50)),
                ('class_description', models.TextField()),
                ('class_date', models.DateField()),
                ('class_time', models.TimeField()),
                ('class_location', models.CharField(default='Revolt Annex', max_length=50)),
            ],
            options={
                'verbose_name': 'Class listing',
                'verbose_name_plural': 'Class Listings',
            },
        ),
        migrations.CreateModel(
            name='Nearby_accomodations',
            fields=[
                ('accom_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('accom_type', models.CharField(choices=[('Hotel', 'Hotel'), ('Air-BNB', 'Air-BNB'), ('Bed-n-Breakfast', 'Bed-n-Breakfast'), ('Camping', 'Camping')], default='', max_length=255)),
                ('accom_distance', models.FloatField()),
                ('accom_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('accom_url', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Nearby Accomadation',
                'verbose_name_plural': 'Nearby Accomadations',
            },
        ),
    ]
