# Generated by Django 4.2.6 on 2024-02-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_alter_archivedshowimagedata_archive_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='visual_artist_listing',
            name='image_folder_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
