# Generated by Django 4.2.6 on 2024-02-16 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_visual_artist_listing_image_folder_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music_artist_listing',
            name='artist_genre',
        ),
        migrations.RemoveField(
            model_name='music_artist_listing',
            name='music_artist_image_url',
        ),
        migrations.AddField(
            model_name='archivedresetdata',
            name='archive_reset_vimeo_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='music_artist_listing',
            name='music_show_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='music_artist_listing',
            name='music_supporting_artist',
            field=models.TextField(blank=True, default=''),
        ),
    ]
