# Generated by Django 4.2.1 on 2023-06-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0012_extra_curriucular_listing_nearby_accomodations'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_artist_listing',
            name='show_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
