# Generated by Django 4.2.6 on 2024-02-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_remove_music_artist_listing_artist_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community_classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, default='', max_length=50)),
                ('class_teacher', models.CharField(default='', max_length=50)),
                ('class_description', models.TextField()),
                ('class_day', models.CharField(blank=True, max_length=30, null=True)),
                ('class_time', models.TimeField()),
                ('class_location', models.CharField(default='Revolt Annex', max_length=50)),
                ('class_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Class listing',
                'verbose_name_plural': 'Class Listings',
            },
        ),
        migrations.DeleteModel(
            name='Extra_curriucular_listing',
        ),
    ]
