# Generated by Django 4.2.1 on 2023-06-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0013_music_artist_listing_show_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_artist_listing',
            name='show_time',
            field=models.TimeField(),
        ),
    ]
