# Generated by Django 4.2.6 on 2024-02-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_community_classes_delete_extra_curriucular_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='community_classes',
            name='teacher_site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
