# Generated by Django 4.2.1 on 2023-06-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0014_alter_music_artist_listing_show_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='visual_artist_listing',
            name='visual_show_name',
            field=models.CharField(default='Show Title', max_length=50),
        ),
    ]
