# Generated by Django 4.2.1 on 2023-06-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0015_visual_artist_listing_visual_show_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music_artist_listing',
            options={'ordering': ['-show_date'], 'verbose_name': 'Musician', 'verbose_name_plural': 'Musicians'},
        ),
    ]
