# Generated by Django 4.2.1 on 2023-07-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0016_alter_music_artist_listing_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heads_up_music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('artist_name', models.TimeField()),
                ('event_description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'HUM Event',
                'verbose_name_plural': 'HUM Events',
                'ordering': ['event_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='extra_curriucular_listing',
            options={'ordering': ['class_date'], 'verbose_name': 'Class listing', 'verbose_name_plural': 'Class Listings'},
        ),
        migrations.AlterModelOptions(
            name='music_artist_listing',
            options={'ordering': ['show_date'], 'verbose_name': 'Musician', 'verbose_name_plural': 'Musicians'},
        ),
        migrations.AlterModelOptions(
            name='visual_artist_listing',
            options={'ordering': ['show_date_start'], 'verbose_name': 'Visual Artist', 'verbose_name_plural': 'Visual Artists'},
        ),
    ]
