# Generated by Django 4.2.1 on 2023-07-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0017_heads_up_music_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_curriucular_listing',
            name='class_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
