# Generated by Django 4.2.1 on 2023-07-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0019_alter_heads_up_music_artist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_curriucular_listing',
            name='image_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='music_artist_listing',
            name='image_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='visual_artist_listing',
            name='image_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
