# Generated by Django 4.2.1 on 2023-07-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0021_remove_music_artist_listing_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra_curriucular_listing',
            name='class_artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='heads_up_music',
            name='artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='music_artist_listing',
            name='music_artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='visual_artist_listing',
            name='visual_artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
