# Generated by Django 4.2.1 on 2023-08-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0022_alter_extra_curriucular_listing_class_artist_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receive_email_updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailform_email', models.EmailField(max_length=255)),
                ('emailform_name', models.CharField(blank=True, max_length=50, null=True)),
                ('emailform_consent', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='extra_curriucular_listing',
            name='class_artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='heads_up_music',
            name='artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='music_artist_listing',
            name='music_artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='visual_artist_listing',
            name='visual_artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
