# Generated by Django 4.2.1 on 2023-08-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0023_receive_email_updates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receive_email_updates',
            name='emailform_consent',
            field=models.BooleanField(default=True),
        ),
    ]
