# Generated by Django 4.2.4 on 2023-08-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0024_alter_receive_email_updates_emailform_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivedshowimagedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_show_name', models.CharField(max_length=50)),
                ('archive_artist_name', models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Archiveimagefiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_image', models.ImageField(upload_to='media/')),
                ('archive_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.archivedshowimagedata')),
            ],
        ),
    ]
