# Generated by Django 4.2.4 on 2023-08-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0026_alter_archivedshowimagedata_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extra_curriucular_listing',
            options={'verbose_name': 'Class listing', 'verbose_name_plural': 'Class Listings'},
        ),
        migrations.AlterField(
            model_name='extra_curriucular_listing',
            name='class_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
