# Generated by Django 4.2.4 on 2023-08-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0027_alter_extra_curriucular_listing_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extra_curriucular_listing',
            old_name='class_date',
            new_name='class_day',
        ),
    ]
