# Generated by Django 4.2.4 on 2023-09-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0029_alter_visual_artist_listing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visual_artist_listing',
            name='vis_artist_bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
