# Generated by Django 4.2.4 on 2023-09-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0030_alter_visual_artist_listing_vis_artist_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='VimeoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
