# Generated by Django 4.2.4 on 2023-10-05 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0031_vimeovideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive_email_updates',
            name='emailform_message',
            field=models.TextField(default=django.utils.timezone.now, max_length=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receive_email_updates',
            name='emailform_subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
