# Generated by Django 4.2.6 on 2023-10-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0031_vimeovideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receive_email_updates',
            name='emailform_message',
            field=models.TextField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='receive_email_updates',
            name='emailform_subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='receive_email_updates',
            name='emailform_consent',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='receive_email_updates',
            name='emailform_email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
