# Generated by Django 4.2.4 on 2023-10-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0032_receive_email_updates_emailform_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receive_email_updates',
            name='emailform_consent',
            field=models.BooleanField(),
        ),
    ]
